### ISSUE TITLE
Avoid duplication download gradle file

### ISSUE THREAD

**Issue by callmepeanut** [mihaip/dex-method-counts#15]
If you have download gradle file in AndroidStudio, then you can replace
"distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-bin.zip"
 in gradle/wrapper/gradle-wrapper.properties by
"distributionUrl=https\://services.gradle.org/distributions/gradle-2.4-all.zip"
then the gradle file would not need to download again.

This tip may be useful to the developers in counties which has limited access to gradle.org

**Comment by sschuberth** [comment]
Note that, however, gradle-2.4-all.zip is *much* bigger than gradle-2.4-bin.zip. So if you do not already have gradle-2.4-all.zip in use, such a chance would in fact create more traffic for first-time users.

**Comment by callmepeanut** [comment]
Got it. This tip is only fit for those who haven't a global proxy and have download gradle-x.x-all.zip file manual before.
