### ISSUE TITLE
MultiDex / ART support

### ISSUE THREAD

**Issue by mttkay** [mihaip/dex-method-counts#16]
It doesn't appear that the script supports builds that result in multiple dex files, where classes are segmented into a primary dex file and additional dex files. The script reports only 22K methods, which I believe to be merely the methods from the primary dex (mostly our own application minus libraries.)

The Android tool chain will generate multiple DEX files when your minSdkLevel is Lollipop / 21 since that is how ART deals with library code (one dex per dependency), and also when you have the multidex switch enabled.

**Comment by sschuberth** [comment]
Multi-dex support was added in https://github.com/mihaip/dex-method-counts/commit/a18e3f560d1a70b1c17dfdacaed5bff8025f8eaf and I can confirm that the tool reports more than 64k methods for our mutli-dex APKs.

**Comment by mttkay** [comment]
Great news, thanks! Any idea yet when this might hit Central? I'm very
interested in this enhancement.

Thanks again.

**Comment by sschuberth** [comment]
I'm not aware that this project publishes its binaries to Maven Central or Bintray / JCenter. There is for example [this artifact](https://bintray.com/sloy/maven/dex-method-counts/view), but that's not the official release as it seems.

**Comment by mttkay** [comment]
Ah fair enough. Thanks.
