### ISSUE TITLE
Support "quiet" or "simple" mode

### ISSUE THREAD

**Issue by dambrisco** [mihaip/dex-method-counts#19]
Would be great to have a switch that enables a mode which prints *only* the total method count. I've added this functionality in [my fork](/dambrisco/dex-method-counts) but it constitutes some rather reaching changes to the code base that I'm not sure fit the pattern you're currently using.

**Comment by callmepeanut** [comment]
I solve this using a shell:
```
echo "Debug: "
./dex-method-counts path/to/debug/apk | tail -1

echo "Release: "
./dex-method-counts path/to/release/apk | tail -1

```

**Comment by mihaip** [comment]
Using the `--max-depth=0` flag trims down the output to just the root. For incorporating the output into other scripts, I think an approach like #18 where it can be more easily machine-parsed is more appropriate.
