### ISSUE TITLE
Version number is hardcoded

### ISSUE THREAD

**Issue by UnoShintaro** [mihaip/dex-method-counts#24]
Version number of dex-method-counts is hardcoded as "1.0" in every versions.
https://github.com/mihaip/dex-method-counts/blob/master/src/info/persistent/dex/Main.java#L203

I'd like to use this useful tool in my daily job and I have to get permission from the security office to do that.
They told me they need managable version number of the object for tracking purpose, so hardcoded one is not acceptable.

**Comment by mihaip** [comment]
I've increased the version number to 1.5 to reflect recent enhancements (field counts, output format), hope that's good enough for your security office.
