### ISSUE TITLE
can't find dex-method-counts.jar

### ISSUE THREAD

**Issue by bu2zhouzhu** [mihaip/dex-method-counts#34]
I git clone this repo to my computer. I enter dex-method-counts/ folder and execute ./dex-method-counts /path/to/my.apk in linux shell and get an error says "can't find dex-method-counts.jar".

What I did wrong? How to solve it and get right output?

**Comment by mihaip** [comment]
You need to build the project first (with Ant or Gradle, see the instructions in the README).
