### ISSUE TITLE
publish to central?

### ISSUE THREAD

**Issue by spyhunter99** [mihaip/dex-method-counts#38]
can you publish this to central?

**Comment by mihaip** [comment]
What is central?

**Comment by spyhunter99** [comment]
Maven central

**Comment by spyhunter99** [comment]
i can help facilitate if you want.

**Comment by spyhunter99** [comment]
https://oss.sonatype.org/content/groups/public/com/github/spyhunter99/dex-method-counts/2.0.0/

published from my fork
