### ISSUE TITLE
Add Windows instructions

### ISSUE THREAD

**Issue by FWest98** [mihaip/dex-method-counts#5]
Windows doesn't support the runfile you provided. You can make a .bat file, or provide the different code for Windows:

java -jar [path-to-generated-jar (./build/jar/....)] [filename to inspect]

**Comment by shriduttkothari** [comment]
@echo off
REM author shriduttkothari@gmail.com
ant jar && java -jar build/jar/dex-method-counts.jar %1

**Comment by tushatpatil293** [comment]
For windows:
-> Add path to apache-ant/bin to Environment variable
-> make sure you have cygwin
-> run >>> ant jar  in cmd at path   \<somepath>\dex-method-counts-master
  a jar will be generated at \dex-method-counts-master\build\jar

-> open cygwin.bat
-> access the path for dex-method-counts-master folder.. <better to keep is simple. i kept it in c: directly>

-> execute   $ ./dex-method-counts <path/to/App.apk>. here path to apk better to keep it inside the  dex-method-counts-master folder to avoid issues related to path in cygwin.
 and here you go :)

**Comment by mihaip** [comment]
Done by 367330cb5c330faf13e835e469a6c81a5e8ec3e9
