### ISSUE TITLE
单独下载 matrix-apk-canary-0.4.10.jar 失败

### ISSUE THREAD

**Issue by rootiny** [mihaip/dex-method-counts#50]
在 https://github.com/Tencent/matrix#matrix_cn 页面单独下载 matrix-apk-canary-0.4.10.jar 失败
浏览器提示:
> 载入页面时与 d29vzk4ow07wi7.cloudfront.net 的连接中断。

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

**Comment by mihaip** [comment]
This project does not depend on matrix (or anything else), so I don’t think this is related.
