### ISSUE TITLE
Project failed to build, can I still use?

### ISSUE THREAD

**Issue by alexblack** [mihaip/dex-method-counts#9]
Hi, my project has failed to build due to too many methods, can I use this tool to pinpoint the culprit?  I'm not sure how to run it given I don't have an APK file, thanks!

**Comment by mihaip** [comment]
Depending on your build process is structured, you could point at the `.jar` that is created as in input to the dex-ing process. You could also roll back the change that put you over the method limit, and see where the most number of methods were before that point.
